"""add power to heroes

Revision ID: c72e2c064553
Revises: 89b1390dfafd
Create Date: 2026-08-29 11:11:36.115915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72e2c064553'
down_revision: Union[str, Sequence[str], None] = '89b1390dfafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('power', sa.String(), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'power')
    # ### end Alembic commands ###
